module.exports = {
  GOVERNORATES: ['Tunis', 'Ariana', 'Ben Arous', 'Manouba', 'Nabeul', 'Zaghouan', 'Bizerte', 'Beja', 'Jendouba', 'Kef', 'Siliana', 'Sousse', 'Monastir', 'Mahdia', 'Sfax', 'Kairouan', 'Kasserine', 'Sidi Bouzid', 'Gabes', 'Medenine', 'Tataouine', 'Gafsa', 'Tozeur', 'Kebili'],
  CATEGORIES: ['electronique', 'informatique', 'maison', 'vetements', 'vehicules', 'livres', 'loisirs', 'bebe', 'sport', 'beaute', 'services_pro', 'artisanat', 'cours', 'freelance', 'musique', 'animaux', 'agriculture', 'autre'],
  CATEGORY_LABELS: {
    electronique: 'Électronique',
    informatique: 'Informatique',
    maison: 'Maison & Jardin',
    vetements: 'Vêtements & Accessoires',
    vehicules: 'Véhicules',
    livres: 'Livres & Magazines',
    loisirs: 'Loisirs & Divertissement',
    bebe: 'Bébé & Enfant',
    sport: 'Sport & Fitness',
    beaute: 'Beauté & Santé',
    services_pro: 'Services Professionnels',
    artisanat: 'Artisanat',
    cours: 'Cours & Formation',
    freelance: 'Freelance',
    musique: 'Musique & Instruments',
    animaux: 'Animaux',
    agriculture: 'Agriculture',
    autre: 'Autre'
  },
  OFFER_TYPES: ['bien', 'service'],
  CONDITIONS: ['neuf', 'comme_neuf', 'bon', 'acceptable', 'pour_pieces'],
  CONDITION_LABELS: { neuf: 'Neuf', comme_neuf: 'Comme neuf', bon: 'Bon état', acceptable: 'Acceptable', pour_pieces: 'Pour pièces' },
  DEAL_STATUSES: ['proposed', 'counter_offered', 'accepted', 'meeting_scheduled', 'completed', 'cancelled', 'disputed', 'expired'],
  BADGES: ['new', 'verified', 'trusted', 'super_exchanger', 'ambassador', 'founder'],
  BADGE_LABELS: { new: 'Nouveau', verified: 'Vérifié', trusted: 'De confiance', super_exchanger: 'Super Échangeur', ambassador: 'Ambassadeur', founder: 'Fondateur' },
  PAYMENT_METHODS: ['cash', 'flouci', 'd17', 'bank_transfer'],
  MAX_PHOTOS: 8,
  MAX_FILE_SIZE: 5 * 1024 * 1024,
  DEFAULT_PAGE_SIZE: 20,
  OFFER_EXPIRY_DAYS: 30,
  DEAL_EXPIRY_DAYS: 7,
  BOOST_DURATION_HOURS: 24,
};
